// Wonder Lab american history data. Generated by tools/build_extras.py
// Years are never `found` — see check_history and .work/BRIEF-ancient.md.
// 0 facts across 0 sections.
const AMERICA = [];
globalThis.AMERICA = AMERICA;
