// The human body half of Wonder Lab.
//
// Built around `tryit` — a 30-second experiment on your own body, no equipment.
// That category tests as the highest-retention thing you can put in front of a
// nine-year-old, because the evidence is their own arm.
//
// `animal` links a body fact to a species card, which is what stitches the two
// halves of the app into one thing instead of two: your ear bones vs a whale's,
// your bite vs a crocodile's.
//
// Every figure here is a mainstream, well-established one. Where sources vary
// (skin surface area, number of taste buds) the accepted range is given rather
// than the most impressive end of it.

const BODY = [
  // ── BRAIN & NERVES ──
  { section: 'brain', cat: 'weird',
    text: 'Your brain is about 60% fat, which makes it the fattiest organ you own.',
    more: 'That fat is not spare padding — it is structural. Much of it forms the insulating sheath wrapped around your nerve fibres, and the membranes every brain cell is built from.' },
  { section: 'brain', cat: 'speed',
    text: 'Signals race along your nerves at up to about 270 mph (430 km/h) — faster than a Formula 1 car.',
    more: 'Not all nerves are quick. The fibres carrying sharp pain are among the fastest; the ones carrying dull ache crawl along at walking pace. That is why you snatch your hand back from something hot before it properly hurts.',
    animal: 'cheetah' },
  { section: 'brain', cat: 'size',
    text: 'Your brain is roughly the size of two clenched fists held together, and weighs about as much as a small pineapple.' },
  { section: 'brain', cat: 'tryit',
    text: 'Your brain quietly hides a hole in your vision, and you can catch it doing it.',
    tryit: 'Draw a dot and a cross about 6 inches apart on paper. Close your right eye, stare at the cross with your left, and slowly move the paper toward your face. The dot vanishes — that is your blind spot, where the nerve leaves the eye. Your brain paints over the gap so smoothly you never notice.' },
  { section: 'brain', cat: 'tryit',
    text: 'You can make your own arm float upward without trying.',
    tryit: 'Stand in a doorway and press the backs of both hands hard against the frame for 45 seconds. Step forward and relax. Your arms drift up on their own — the muscles are still firing after your brain stopped asking.' },
  { section: 'brain', cat: 'oops',
    text: 'Brain freeze is not your brain getting cold. It is a blood vessel in the roof of your mouth over-reacting.',
    more: 'Something very cold makes an artery up there narrow and then rapidly widen again. Nerves nearby report the change, and your brain misreads where the signal came from — so you feel it in your forehead instead of your palate.' },
  { section: 'brain', cat: 'oops',
    text: 'Pins and needles happen when you squash a nerve, not when your foot "falls asleep".',
    more: 'Pressure interrupts the nerve\'s signalling. When you shift and the pressure lifts, the nerve fires off a burst of confused messages all at once — which your brain reads as fizzing.' },
  { section: 'brain', cat: 'sleep',
    text: 'That falling jolt just as you drift off has a name: a hypnic jerk. Most people get them.',
    more: 'Nobody has fully settled why they happen. One well-supported idea is that as your muscles go slack, the change is briefly misread as falling, and your body responds by catching itself.' },

  // ── HEART & BLOOD ──
  { section: 'heart', cat: 'record',
    text: 'Your heart beats roughly 100,000 times a day and has never once taken a day off.',
    more: 'It manages that because it rests between every single beat. Add all those tiny pauses together and the heart is actually "off duty" for a large part of every day.' },
  { section: 'heart', cat: 'tryit',
    text: 'You can find your own pulse in about five seconds.',
    tryit: 'Put two fingers — not your thumb, it has its own pulse — on the thumb side of your wrist. Count the beats for 15 seconds and multiply by four. Now run on the spot for a minute and try again.' },
  { section: 'heart', cat: 'size',
    text: 'Your heart is about the size of your own closed fist. It grows as you do, so it always roughly matches.' },
  { section: 'heart', cat: 'weird',
    text: 'Laid end to end, the blood vessels in one person would stretch tens of thousands of miles.',
    more: 'Almost all of that length is capillaries — vessels so narrow that red blood cells have to squeeze through in single file.' },
  { section: 'heart', cat: 'samesame',
    text: 'Your heart has four chambers. So does a crocodile\'s — most reptiles have three.',
    animal: 'saltwater-crocodile' },
  { section: 'heart', cat: 'food',
    text: 'Red blood cells carry oxygen using iron. That is genuinely why blood tastes faintly metallic.' },

  // ── BONES & MUSCLES ──
  { section: 'bones', cat: 'weird',
    text: 'You were born with about 300 bones. You now have 206. You did not lose them — some fused together.',
    more: 'A baby\'s skull is several separate plates with gaps between them, which is what lets the head flex on the way out and then keep growing. They knit together over the first couple of years.' },
  { section: 'bones', cat: 'size',
    text: 'Your smallest bone is inside your ear and is about the size of a grain of rice.',
    more: 'It is called the stapes, or stirrup, because that is exactly what it looks like. Three tiny bones in a chain amplify the wobble of your eardrum and pass it inward.' },
  { section: 'bones', cat: 'record',
    text: 'Bone is astonishingly strong for its weight — pound for pound, stronger than steel.',
    more: 'It manages that by being a composite: hard mineral for stiffness, stretchy collagen fibres for toughness. Pure mineral would shatter; pure collagen would bend.' },
  { section: 'bones', cat: 'tryit',
    text: 'Your jaw muscle is one of the strongest muscles you own, for its size.',
    tryit: 'Put your fingers on your temples and bite down gently. Feel that bulge? That is your temporalis muscle — it runs up the side of your skull, which is why chewing makes your head move.' },
  { section: 'bones', cat: 'weird',
    text: 'Over half the bones in your body are in your hands and feet.',
    more: 'Twenty-seven in each hand, twenty-six in each foot. All those small bones are what let your hand wrap around a ball and your foot roll through a step.' },
  { section: 'bones', cat: 'samesame',
    text: 'A giraffe has exactly the same number of neck bones as you do: seven.',
    more: 'Theirs are just enormously long. Almost every mammal has seven, from a mouse to a whale.',
    animal: 'giraffe' },
  { section: 'bones', cat: 'oops',
    text: 'Growing pains are real, but they are not the bone stretching.',
    more: 'They are usually muscle aches in the legs after an active day, and they tend to strike in the evening. Bone growth itself is far too slow to feel.' },

  // ── LUNGS & BREATHING ──
  { section: 'lungs', cat: 'size',
    text: 'Unfolded flat, the inside surface of your lungs would cover a good chunk of a tennis court.',
    more: 'All that area is packed into your chest as hundreds of millions of tiny air sacs called alveoli — each one thinner than a sheet of tissue paper so oxygen can slip straight through into the blood.' },
  { section: 'lungs', cat: 'tryit',
    text: 'You cannot hum while holding your nose.',
    tryit: 'Try it. Humming needs air moving out through your nose, so pinching it shut stops the sound instantly. Now try to hum and swallow at the same time — also impossible.' },
  { section: 'lungs', cat: 'weird',
    text: 'Your left lung is smaller than your right, because your heart is sitting in the space.',
    more: 'The left lung has two lobes; the right has three. That notch in the left one has a name — the cardiac notch.' },
  { section: 'lungs', cat: 'oops',
    text: 'A hiccup is your diaphragm twitching, and the "hic" is your voice box slamming shut.',
    more: 'The diaphragm is the big sheet of muscle under your lungs. When it spasms you gulp air suddenly, and your vocal cords snap closed about a thirty-fifth of a second later. That snap is the sound.' },
  { section: 'lungs', cat: 'samesame',
    text: 'You breathe in and out through the same tubes. A bird\'s air flows one way, in a loop.',
    more: 'That one-way system means a bird gets fresh air across its lungs even while breathing out, which is part of how some can fly at altitudes where a person would black out.',
    animal: 'bar-tailed-godwit' },

  // ── SENSES ──
  { section: 'senses', cat: 'weird',
    text: 'The tongue map in old textbooks — sweet at the tip, bitter at the back — is simply wrong.',
    more: 'Every part of your tongue can detect every taste. The diagram came from a mistranslation of a German study and then got copied into books for decades.' },
  { section: 'senses', cat: 'tryit',
    text: 'Most of what you call taste is actually smell.',
    tryit: 'Pinch your nose shut and eat a jelly bean without looking. You will get sweet, and almost nothing else. Let go of your nose mid-chew and the flavour arrives all at once.' },
  { section: 'senses', cat: 'tryit',
    text: 'Your sense of temperature is relative, and you can fool it in under a minute.',
    tryit: 'Fill three bowls: cold, lukewarm, warm. Put one hand in cold and one in warm for 30 seconds, then plunge both into the lukewarm one. The same water feels hot to one hand and cold to the other.' },
  { section: 'senses', cat: 'senses',
    text: 'Your eyes can tell apart something like a million different shades of colour.',
    animal: 'mantis-shrimp' },
  { section: 'senses', cat: 'weird',
    text: 'You have a sense most people never get counted: proprioception, knowing where your body is without looking.',
    tryit: 'Close your eyes and touch your nose with one finger. You did not need to see your hand — that is proprioception, reporting from every joint and muscle.' },
  { section: 'senses', cat: 'oops',
    text: 'Motion sickness happens when your eyes and your ears disagree.',
    more: 'Reading in a moving car, your eyes report a still page while the balance organs in your inner ear report bouncing. Your brain gets two contradictory stories and responds by making you feel ill.' },
  { section: 'senses', cat: 'samesame',
    text: 'A cat sees far better than you in near-dark — but you see far more colour.',
    animal: 'tiger' },

  // ── SKIN, HAIR & NAILS ──
  { section: 'skin', cat: 'record',
    text: 'Skin is your largest organ. Spread flat, an adult\'s is roughly the size of a bath towel.' },
  { section: 'skin', cat: 'gross',
    text: 'You shed skin cells constantly — a large share of household dust is you.',
    more: 'You replace your outer layer of skin steadily over roughly a month, so the surface you are wearing now is not the one you had last term.' },
  { section: 'skin', cat: 'tryit',
    text: 'Your fingertips are far more sensitive than your back, and you can measure the difference.',
    tryit: 'Bend a paperclip into a U with the ends about 1 cm apart. Touch both ends to a fingertip — you feel two points. Do the same on your forearm or back and it feels like one. Fingertips have far more touch sensors packed in.' },
  { section: 'skin', cat: 'weird',
    text: 'Fingers wrinkle in the bath on purpose. It is your nervous system doing it, not water soaking in.',
    more: 'The nerves trigger tiny blood vessels under the skin to narrow, pulling the surface into ridges. Wrinkled fingertips grip wet things better — the pattern works like tyre tread.' },
  { section: 'skin', cat: 'weird',
    text: 'Goosebumps are a leftover reflex for fluffing up fur you no longer have.',
    more: 'Each tiny muscle pulls a hair upright. On a cat or a bird it traps warm air and makes the animal look bigger. On you it just makes bumps.' },
  { section: 'skin', cat: 'oops',
    text: 'Itching has its own dedicated nerve pathway, separate from pain.',
    more: 'Which is why scratching works only briefly — it floods the area with a different sensation that drowns out the itch signal for a moment.' },

  // ── EATING & DIGESTING ──
  { section: 'gut', cat: 'gross',
    text: 'Your stomach acid is strong enough to damage metal — and your stomach relines itself so it does not digest you.',
    more: 'A layer of mucus and a fresh supply of cells replace the lining continuously. Without that, the acid would start on the stomach wall itself.' },
  { section: 'gut', cat: 'size',
    text: 'Your small intestine is not small. Stretched out, it is several times your own height.',
    more: 'It is called "small" because it is narrow, not short. Its inner surface is folded and fringed into millions of tiny projections, which is how so much absorbing surface fits inside you.' },
  { section: 'gut', cat: 'weird',
    text: 'Swallowing is not gravity. Muscles squeeze food along in a wave, so you could swallow upside down.',
    more: 'That wave is called peristalsis, and it runs the whole length of your gut. Astronauts eat and drink normally in freefall for exactly this reason.' },
  { section: 'gut', cat: 'gross',
    text: 'Your gut is home to trillions of bacteria, and you need them.',
    more: 'They help break down food your own enzymes cannot handle and make certain vitamins for you. Carried together they weigh a surprising amount.' },
  { section: 'gut', cat: 'tryit',
    text: 'Your mouth starts digesting before you swallow.',
    tryit: 'Chew a plain cracker slowly and keep it in your mouth for a full minute without swallowing. It turns sweet. An enzyme in your saliva is already cutting the starch into sugar.' },
  { section: 'gut', cat: 'samesame',
    text: 'A cow needs four stomach chambers to get through grass. You get by with one.',
    animal: 'reindeer' },

  // ── GERM FIGHTERS ──
  { section: 'defence', cat: 'weird',
    text: 'A fever is not the illness. It is your body deliberately turning the heat up.',
    more: 'Many germs breed best at your normal temperature, and your immune cells work faster when it is warmer. Your body raises the thermostat on purpose.' },
  { section: 'defence', cat: 'defence',
    text: 'White blood cells hunt. Some chase bacteria down and swallow them whole.',
    more: 'The cell flows around the invader, engulfs it, and breaks it apart inside. This is called phagocytosis — literally "cell eating".' },
  { section: 'defence', cat: 'gross',
    text: 'A scab is a temporary lid built out of your own blood.',
    more: 'Platelets clump at the tear and lay down a mesh of fibres, blood cells get caught in it, and the whole plug dries hard while new skin is built underneath.' },
  { section: 'defence', cat: 'weird',
    text: 'Sneezes leave your nose at genuinely impressive speed, and you cannot keep your eyes open for one.',
    more: 'The eye-closing is a reflex bundled with the sneeze. Nobody has found a good reason for it — your eyes would not pop out, despite the playground legend.' },
  { section: 'defence', cat: 'oops',
    text: 'An allergy is your immune system attacking something harmless by mistake.',
    more: 'Pollen and peanuts are not dangerous. The reaction — the itching, swelling and sneezing — is entirely your own defences overreacting.' },

  // ── GROWING UP ──
  { section: 'growing', cat: 'weird',
    text: 'You grow fastest while you are asleep. Literally overnight.',
    more: 'Most growth hormone is released during deep sleep. You are also measurably taller in the morning than at bedtime, because the discs in your spine decompress overnight.' },
  { section: 'growing', cat: 'tryit',
    text: 'You shrink a little every single day.',
    tryit: 'Measure your height first thing in the morning, then again just before bed. Most people lose up to a centimetre over the day as the cushions between the bones of the spine squash down.' },
  { section: 'growing', cat: 'babies',
    text: 'Every person started as a single cell, too small to see without a microscope.' },
  { section: 'growing', cat: 'weird',
    text: 'Babies have no kneecaps at birth — not bony ones anyway.',
    more: 'They start as cartilage, the same bendy stuff as the tip of your nose, and harden into bone over several years. Bendy knees survive a lot of crawling.' },
  { section: 'growing', cat: 'sleep',
    text: 'A nine-year-old needs 9 to 12 hours of sleep. Adults need less, which is deeply unfair.',
    more: 'Your body clock also shifts later as you become a teenager, so the urge to stay up is not laziness — the timing genuinely moves.' },
  { section: 'growing', cat: 'weird',
    text: 'You had more taste buds as a toddler than you do now, spread over a wider area.',
    more: 'Which is a real reason strong flavours felt overwhelming when you were small, and why sprouts get less offensive as you grow.' },
];
