// Wonder Lab world history data. Generated by tools/build_extras.py
// Years are never `found` — see check_history and .work/BRIEF-ancient.md.
// 0 facts across 0 sections.
const WORLD = [];
globalThis.WORLD = WORLD;
